[package]
name = "skript"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1.0"
inquire = "0.6"
rustyline = "12.0"
